{{- if .Values.storage.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-influxdb-pv
  labels:
    app.kubernetes.io/managed-by: "Helm"  # Required by Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}  # Required by Helm
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}  # Required by Helm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/influxdb  # Replace with a valid path on your node
{{- end }}
