# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
namespace: wpd
env:
  HOST_IP: # IP address of the target Edge Node, example: HOST_IP: 10.100.100.100
  http_proxy: # example: http_proxy: http://proxy.example.com:891
  https_proxy: # example: http_proxy: http://proxy.example.com:891
  MINIO_ACCESS_KEY: # example: MINIO_ACCESS_KEY: intel1234
  MINIO_SECRET_KEY: # example: MINIO_SECRET_KEY: intel1234
  POSTGRES_PASSWORD: # example: POSTGRES_PASSWORD: intel1234
  S3_STORAGE_PORT: 31800 # Original port: 30800
webrtcturnserver:
    username: # example: username: myuser
    password: # example: password: mypassword
gpu:
   enabled: true
   type: "gpu.intel.com/i915"
   count: 1
config:
  prometheus:
    ext:
      prometheus_port: "31909" # Original port: 30909
  otel_collector:
    ext:
      otlp_grpc_port: "31417" # Original port: 30417
      otlp_http_port: "31418" # Original port: 30418
      otlp_prometheus_endpoint_port: "31464" # Original port: 30464
  mediamtx:
    ext:
      mediamtx_port: "32111" # Original port: 31111
      mediamtx_sdp_port: "32112" # Original port: 31112
      mediamtx_api_port: "32222" # Original port: 31222
  coturn:
    ext:
      coturn_tcp_port: "31478" # Original port: 30478
      coturn_udp_port: "31478" # Original port: 30478
  dlstreamer_pipeline_server:
    ext:
      rest_api_port: "31107" # Original port: 30107
      rtsp_output_port: "31125" # Original port: 30125
  model_registry:
    ext:
      port: "32102" # Original port: 32002
